type: object
properties:
  id:
    type: integer
  nome:
    type: string
  dataNascimento:
    type: string
    format: date
  sexo:
    type: string
    enum: [M, F, O]
  etnia:
    type: string
  telefone:
    type: string
  email:
    type: string
    format: email
required:
  - nome
  - dataNascimento
