openapi: 3.0.4
info:
  title: Sistema Hospitalar API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: Pacientes
  - name: Medicos
  - name: Enfermidades
  - name: Consultas
  - name: Internacoes
  - name: Quartos
  - name: Medicamentos
  - name: Prescricoes
  - name: EvolucaoClinica
  - name: Epidemias

paths:
  /pacientes:
    $ref: './paths/pacientes.yaml'
  /medicos:
    $ref: './paths/medicos.yaml'
  /enfermidades:
    $ref: './paths/enfermidades.yaml'
  /consultas:
    $ref: './paths/consultas.yaml'
  /internacoes:
    $ref: './paths/internacoes.yaml'
  /quartos:
    $ref: './paths/quartos.yaml'
  /medicamentos:
    $ref: './paths/medicamentos.yaml'
  /prescricoes:
    $ref: './paths/prescricoes.yaml'
  /evolucao-clinica:
    $ref: './paths/evolucao_clinica.yaml'
  /epidemias:
    $ref: './paths/epidemias.yaml'

components:
  schemas:
    Paciente:
      $ref: './schemas/paciente.yaml'
    Medico:
      $ref: './schemas/medico.yaml'
    Enfermidade:
      $ref: './schemas/enfermidade.yaml'
    Consulta:
      $ref: './schemas/consulta.yaml'
    Internacao:
      $ref: './schemas/internacao.yaml'
    Quarto:
      $ref: './schemas/quarto.yaml'
    Medicamento:
      $ref: './schemas/medicamento.yaml'
    Prescricao:
      $ref: './schemas/prescricao.yaml'
    EvolucaoClinica:
      $ref: './schemas/evolucao_clinica.yaml'
    Epidemia:
      $ref: './schemas/epidemia.yaml'
